<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>chapter_12 || Async JavaScript</title>
</head>
<body>




<script>

    /*
     - fetch() bize promise return edir
     promise return edib deyirdi : resolve veya reject
     - endpoint sehvdirse indi
     catch olunub err-ni yaacagini dusunuruk ama
     ele deyil consolda baxsaq reloved olundugunu yani then-in calishdigini
     gorerik.
     niye?
        - cunki catch() - yalniz network errorlarinda calisir.
        misalcun offline-iq veya api-a acces ede bilmirik
        - buradada resource-da herf seffinde reject olunmur
        - evezinde resolve olunub response aliriq.
        - consolda objecti acib baxsaq status codu 404 gorerik.
            yani resource cant be found!!!
        - bunu duzeltmek ucun deye bilerik eyer status 200 deyilse reponse olma
        veya resolve olma
       ve network error olarsada ozu reject edecekdir

      - ve eyer endpoint dogru olarsada bu zaman konsolda status kodu 200 gorerik
      - ama biz consolda object icind datani gormuruk niye ?
            -  proto-nu expand et
                - burada "json" - metodunu goruruk
                  bunu  response objecti uzerinde ist edib datani alacagiq.
                - json() metodu datani getirib parse edir eynen JSON.parse kimi
    */
    fetch('todos/faik.json').then( response => {
        // resolved
        console.log('resolved: ',response);
        // bu metod bize datani getirir eynen JSON.parse kimi
        // const data = response.json(); -> JSON.parse()-da  deyishkene atmishdiq
        // ama burada bu shekilde islemir cunki ----
        // bu promise return etmelidir ona gore
        //  ( JSON.parse() ile sonra biz resolve icinde return edirdik
        // burdada retun etmeliyik
        return  response.json();
    }).then((data) => {
        console.log(data);
    }).catch( err => {
        // rejected
        console.log('rejected: ', err);
    })



</script>
</body>
</html>
