<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>chapter_12 || Async JavaScript</title>
</head>
<body>




<script>
    const getTodos = async () => {
        const response = await fetch('todos/faiks.json');
        const data =  await response.json();

        return data;
    }
    /*
     - custom error  - eyer async func icinde reject etmek istediyimiz
     promis varsa  mesleen json icinde invalid nese varsa ve onu reject
     etmek isteyirikse .catch()  ile edirik
     misalcun error json icinde syntax xetasi ola biler.
     - response.json()-dan gelen error zamani reject olunur yani
      async promise return edir ve catch olunur.
     - ama fetch()- den gelen error ise resolve edilir
      yani .then() icinde qalir success olaraq.
      yani eyer daxil etdiyimiz endpoint yanlish ise bele olur.
    */
    getTodos().then(data => {
        console.log(data);
    }).catch(err => {
        // err.message bize msg verer.
        console.log(err.message);
    });
</script>
</body>
</html>
